import { useEffect, useState } from 'react'
import { Scene } from '@/components/Scene'
import { UIOverlay } from '@/components/UIOverlay'
import { useArchitectureStore } from '@/store/architectureStore'
import { sampleArchitecture } from '@/lib/sampleData'

function App() {
  const { setArchitecture, isLoading, error } = useArchitectureStore()
  const [loadingSource, setLoadingSource] = useState<string | null>(null)

  useEffect(() => {
    // Try to load architecture from /architecture.json (generated by CLI --input)
    // Fall back to sample data if not found
    async function loadArchitecture() {
      setLoadingSource('Loading architecture...')

      try {
        const response = await fetch('/architecture.json')
        if (response.ok) {
          const data = await response.json()
          if (data.architecture) {
            setArchitecture(data.architecture)
            setLoadingSource(null)
            console.log('Loaded architecture from /architecture.json')
            return
          }
        }
      } catch (e) {
        // File not found or invalid, fall back to sample
        console.log('No architecture.json found, using sample data')
      }

      // Fall back to sample architecture
      setArchitecture(sampleArchitecture)
      setLoadingSource(null)
    }

    loadArchitecture()
  }, [setArchitecture])

  return (
    <div className="relative w-full h-full bg-soar-darker">
      {/* 3D Scene */}
      <Scene />

      {/* UI Overlay */}
      <UIOverlay />

      {/* Loading overlay */}
      {(isLoading || loadingSource) && (
        <div className="absolute inset-0 flex items-center justify-center bg-soar-darker/80 z-50">
          <div className="flex flex-col items-center gap-4">
            <div className="spinner w-12 h-12" />
            <p className="text-soar-accent font-mono">{loadingSource || 'Analyzing architecture...'}</p>
          </div>
        </div>
      )}

      {/* Error display */}
      {error && (
        <div className="absolute top-4 left-1/2 -translate-x-1/2 z-50">
          <div className="glass-panel px-4 py-2 border-soar-error/50">
            <p className="text-soar-error text-sm">{error}</p>
          </div>
        </div>
      )}
    </div>
  )
}

export default App
